### PR TITLE
Rebuild for Python 3.7, update CI, build with only one version of numpy

### PR DESCRIPTION
**Pull request by xylar**
Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

Working off of #7 but don't have permission to push to that branch

closes #7

### CODE REVIEW

**Comment by dnadeau4** [comment]
@conda-forge-admin, please rerender

**Comment by dnadeau4** [comment]
You seem to have old numpy 1.9 in the .ci-support.

**Comment by dnadeau4** [comment]
@xylar this should have worked, so I reran the workflow on circleci.  Everything is ok with numpy 1.9.

**Comment by xylar** [comment]
Thanks! Yeah, I think the reversion to numpy 1.9 is the expected behavior -- you're supposed to build against the oldest compatible version (https://conda-forge.org/docs/meta.html#building-against-numpy).

It seems like we're almost there...

**Comment by xylar** [comment]
I think the bot's PR maybe failed because `cdms2` wasn't there yet.  Does that seem plausible?

**Comment by xylar** [comment]
I don't believe we want the `.np1.9` included in the version number.  I'm going to take it out.  Please let me know if you object.

**Comment by xylar** [comment]
Hopefully there's no objection to me being added as a maintainer.  If so, I'm happy to take myself off again.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
